# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "CASTIEL2 Multi-GPU AI"
copyright = "2026, The contributors"
author = "The contributors"
github_user = "ENCCS"
github_repo_name = ""  # auto-detected from dirname if blank
github_version = "main"
conf_py_path = "/content/"  # with leading and trailing slash

# GitHub repository configuration for the repo role
github_repo_url = "https://github.com/ENCCS/castiel-multi-gpu-ai"
github_branch = "main"
github_root_dir = "content"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # githubpages just adds a .nojekyll file
    "sphinx.ext.githubpages",
    "sphinx_lesson",
    # remove once sphinx_rtd_theme updated for contrast and accessibility:
    "sphinx_rtd_theme_ext_color_contrast",
    "sphinx.ext.todo",
]

# Settings for myst_nb:
# https://myst-nb.readthedocs.io/en/latest/use/execute.html#triggering-notebook-execution
# nb_execution_mode = "cache"
nb_execution_mode = "off"

# https://myst-parser.readthedocs.io/en/latest/syntax/optional.html
myst_enable_extensions = [
    "colon_fence",
    "dollarmath",
    "amsmath",
    "attrs_inline",
    "substitution",
]
myst_dmath_double_inline = True
myst_fence_as_directive = {"mermaid"}
myst_substitutions = {"author": author}
myst_heading_anchors = 4

# Settings for sphinx-copybutton
copybutton_exclude = ".linenos, .gp"

# Add any paths that contain templates here, relative to this directory.
# templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "README*",
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "jupyter_execute",
    "*venv*",
    "_patched",  # generated by patch.py script
]

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"
html_logo = "img/CASTIEL2.png"
html_favicon = "img/favicon.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["overrides.css"]

# HTML context:
from os.path import basename, dirname, realpath, join

html_context = {
    "display_github": True,
    "github_user": github_user,
    # Auto-detect directory name.  This can break, but
    # useful as a default.
    "github_repo": github_repo_name or basename(dirname(dirname(realpath(__file__)))),
    "github_version": github_version,
    "conf_py_path": conf_py_path,
}

html_theme_options = {
    # Toc options
    "collapse_navigation": True,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

# Intersphinx mapping.  For example, with this you can use
# :py:mod:`multiprocessing` to link straight to the Python docs of that module.
# List all available references:
#   python -msphinx.ext.intersphinx https://docs.python.org/3/objects.inv
# extensions.append('sphinx.ext.intersphinx')
# intersphinx_mapping = {
#    #'python': ('https://docs.python.org/3', None),
#    #'sphinx': ('https://www.sphinx-doc.org/', None),
#    #'numpy': ('https://numpy.org/doc/stable/', None),
#    #'scipy': ('https://docs.scipy.org/doc/scipy/reference/', None),
#    #'pandas': ('https://pandas.pydata.org/docs/', None),
#    #'matplotlib': ('https://matplotlib.org/', None),
#    'seaborn': ('https://seaborn.pydata.org/', None),
# }

# add few new directives
from sphinx_lesson.directives import _BaseCRDirective


class SignatureDirective(_BaseCRDirective):
    extra_classes = ["toggle-shown", "dropdown"]


class ParametersDirective(_BaseCRDirective):
    extra_classes = ["dropdown"]


class TypealongDirective(_BaseCRDirective):
    extra_classes = ["toggle-shown", "dropdown"]


class InstructorDirective(_BaseCRDirective):
    extra_classes = ["dropdown"]


class SpoilerDirective(_BaseCRDirective):
    extra_classes = ["important", "dropdown"]


DIRECTIVES = [
    SignatureDirective,
    ParametersDirective,
    TypealongDirective,
    InstructorDirective,
    SpoilerDirective,
]


# Custom role for GitHub repository links
from docutils import nodes
from docutils.parsers.rst import roles


def repo_role(name, rawtext, text, lineno, inliner, options={}, content=[]):
    """Custom role to create GitHub repository links."""
    # Split the text into path and optional custom text
    parts = text.split("|", 1)
    path = parts[0].strip()
    
    # Use custom text if provided, otherwise use the path
    if len(parts) > 1:
        link_text = parts[1].strip()
    else:
        link_text = path
    
    # Construct the GitHub URL
    github_url = f"{github_repo_url}/tree/{github_branch}/{github_root_dir}/{path}"
    
    # Create a reference node with the link
    node = nodes.reference(rawtext, join(github_root_dir, link_text), refuri=github_url, **options)
    return [node], []


def setup_repo_role(app):
    """Setup the repo role."""
    # Add the role to the Sphinx registry
    app.add_role("repo", repo_role)

# pdfembed directive is part of the sphinx-evita project (MIT License)
# Copyright (c) 2025 EVITA project

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass

from docutils import nodes
from docutils.parsers.rst import directives
from sphinx.util.docutils import SphinxDirective


class pdfembed(nodes.General, nodes.Element):
    pass


def align_spec(argument) -> str:
    # Allow left, center, right
    return directives.choice(argument, ("left", "center", "right"))


class PDFEmbedDirective(SphinxDirective):
    """
    Directive to embed a PDF via iframe.
    """

    has_content = False
    required_arguments = 1  # The PDF file path
    optional_arguments = 0
    final_argument_whitespace = False
    option_spec = {
        "height": directives.unchanged,
        "width": directives.unchanged,
        "align": align_spec,
        "id": directives.unchanged,
        "title": directives.unchanged,
        "frameborder": directives.unchanged,
        "scrolling": directives.unchanged,
        "style": directives.unchanged,
    }

    def run(self):
        node = pdfembed()

        # Set the node src to the path from the built HTML.
        # Note: assumes the PDF is copied to _static directory.
        node["src"] = self.arguments[0].strip()
        node["height"] = self.options.get("height", "550vh")
        node["width"] = self.options.get("width", "100%")
        node["align"] = self.options.get("align", "center")
        # node["id"] = self.options.get("id", f"pdf-{uuid.uuid4()}")
        node["title"] = self.options.get("title", "PDF")
        node["frameborder"] = self.options.get("frameborder", "1")
        node["scrolling"] = self.options.get("scrolling", "auto")
        node["style"] = self.options.get("style", "border:1px solid #666CCC")
        return [node]


def html_visit_pdfembed(self, node):
    """Embed in HTML using object or iframe."""
    match getattr(self.builder.config, "pdfembed_html_tag", "object").lower():
        case "iframe":
            # Compose the <iframe> tag
            tag = (
                f'<iframe class="pdfembed" '
                # f'id="{node["id"]}" '
                f'style="{node["style"]}" '
                f'title="{node["title"]}" '
                f'src="{node["src"]}" '
                f'frameborder="{node["frameborder"]}" '
                f'scrolling="{node["scrolling"]}" '
                f'height="{node["height"]}" '
                f'width="{node["width"]}" '
                f'align="{node["align"]}">'
                f"</iframe>"
            )
        case _:
            # Compose the <object> tag
            tag = (
                '<div class="pdfembed">'
                f"<object "
                # f'id="{node["id"]}" '
                f'style="{node["style"]}" '
                f'data="{node["src"]}" '
                f'type="application/pdf" '
                f'height="{node["height"]}" '
                f'width="{node["width"]}" '
                f'title="{node["title"]}" '
                f'align="{node["align"]}">'
                f'<p class="warning">Your browser does not support PDFs. '
                f'<a href="{node["src"]}">Download the PDF</a>.</p>'
                f"</object>"
                "</div>"
            )

    self.body.append(tag)
    raise nodes.SkipNode


def setup(app):
    for obj in DIRECTIVES:
        app.add_directive(obj.cssname(), obj)

    app.add_node(
        pdfembed,
        html=(html_visit_pdfembed, None),
        # Optionally add for other builders
    )
    app.add_directive("pdfembed", PDFEmbedDirective)
    app.add_config_value("pdfembed_html_tag", "object", "html")

    # Setup the repo role
    setup_repo_role(app)

    return {"version": "0.0.1", "parallel_read_safe": True, "parallel_write_safe": True}
